#端口配置
server:
  port: 8080
#Mysql连接池
spring:
  application:
    name: MEET
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '@Wo258852'
      url: jdbc:mysql://101.200.87.110:3306/star?&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: dr # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.test.fx: debug
    org.springframework: warn
    org.apache.ibatis.logging: debug
