#端口配置
server:
  port: 9000
#Mysql连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://49.232.151.78:3306/mysql?&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#mybatis-plus SQL输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
